// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "yawarad": request Resource Client
//
// Command:
// $ goagen
// --design=github.com/itamartempel/yawarad/design
// --out=$(GOPATH)/src/github.com/itamartempel/yawarad
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ListRequestPath computes a request path to the list action of request.
func ListRequestPath() string {

	return fmt.Sprintf("/api/v1/cluster-branching/requests/")
}

// Retrive requests
func (c *Client) ListRequest(ctx context.Context, path string, clusterName *string, fromTime *int, limit *int, requestor *string, skip *int, state *string, toTime *int, type_ *string) (*http.Response, error) {
	req, err := c.NewListRequestRequest(ctx, path, clusterName, fromTime, limit, requestor, skip, state, toTime, type_)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListRequestRequest create the request corresponding to the list action endpoint of the request resource.
func (c *Client) NewListRequestRequest(ctx context.Context, path string, clusterName *string, fromTime *int, limit *int, requestor *string, skip *int, state *string, toTime *int, type_ *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if clusterName != nil {
		values.Set("cluster_name", *clusterName)
	}
	if fromTime != nil {
		tmp33 := strconv.Itoa(*fromTime)
		values.Set("from_time", tmp33)
	}
	if limit != nil {
		tmp34 := strconv.Itoa(*limit)
		values.Set("limit", tmp34)
	}
	if requestor != nil {
		values.Set("requestor", *requestor)
	}
	if skip != nil {
		tmp35 := strconv.Itoa(*skip)
		values.Set("skip", tmp35)
	}
	if state != nil {
		values.Set("state", *state)
	}
	if toTime != nil {
		tmp36 := strconv.Itoa(*toTime)
		values.Set("to_time", tmp36)
	}
	if type_ != nil {
		values.Set("type", *type_)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowRequestPath computes a request path to the show action of request.
func ShowRequestPath(requestID string) string {
	param0 := requestID

	return fmt.Sprintf("/api/v1/cluster-branching/requests/%s", param0)
}

// Retrieve single request by id.
func (c *Client) ShowRequest(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowRequestRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowRequestRequest create the request corresponding to the show action endpoint of the request resource.
func (c *Client) NewShowRequestRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
