// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "yawarad": request-changes Resource Client
//
// Command:
// $ goagen
// --design=github.com/itamartempel/yawarad/design
// --out=$(GOPATH)/src/github.com/itamartempel/yawarad
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"golang.org/x/net/websocket"
	"net/url"
)

// SubscribeRequestChangesPath computes a request path to the subscribe action of request-changes.
func SubscribeRequestChangesPath(requestID string) string {
	param0 := requestID

	return fmt.Sprintf("/api/v1/cluster-branching/requests/%s/ws", param0)
}

// Subscribe to any changes that will happend to a single request by websocket
func (c *Client) SubscribeRequestChanges(ctx context.Context, path string) (*websocket.Conn, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "ws"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	url_ := u.String()
	cfg, err := websocket.NewConfig(url_, url_)
	if err != nil {
		return nil, err
	}
	return websocket.DialConfig(cfg)
}
