// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "yawarad": snapshot-branches Resource Client
//
// Command:
// $ goagen
// --design=github.com/itamartempel/yawarad/design
// --out=$(GOPATH)/src/github.com/itamartempel/yawarad
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ListSnapshotBranchesPath computes a request path to the list action of snapshot-branches.
func ListSnapshotBranchesPath(snapshotID string) string {
	param0 := snapshotID

	return fmt.Sprintf("/api/v1/cluster-branching/snapshots/%s/branches", param0)
}

// Retrive branches that was created from a specific snapshot
func (c *Client) ListSnapshotBranches(ctx context.Context, path string, fromTime *int, limit *int, requestor *string, skip *int, status *string, team *string, toTime *int, type_ *string) (*http.Response, error) {
	req, err := c.NewListSnapshotBranchesRequest(ctx, path, fromTime, limit, requestor, skip, status, team, toTime, type_)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListSnapshotBranchesRequest create the request corresponding to the list action endpoint of the snapshot-branches resource.
func (c *Client) NewListSnapshotBranchesRequest(ctx context.Context, path string, fromTime *int, limit *int, requestor *string, skip *int, status *string, team *string, toTime *int, type_ *string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if fromTime != nil {
		tmp41 := strconv.Itoa(*fromTime)
		values.Set("from_time", tmp41)
	}
	if limit != nil {
		tmp42 := strconv.Itoa(*limit)
		values.Set("limit", tmp42)
	}
	if requestor != nil {
		values.Set("requestor", *requestor)
	}
	if skip != nil {
		tmp43 := strconv.Itoa(*skip)
		values.Set("skip", tmp43)
	}
	if status != nil {
		values.Set("status", *status)
	}
	if team != nil {
		values.Set("team", *team)
	}
	if toTime != nil {
		tmp44 := strconv.Itoa(*toTime)
		values.Set("to_time", tmp44)
	}
	if type_ != nil {
		values.Set("type", *type_)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
