// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "yawarad": snapshot Resource Client
//
// Command:
// $ goagen
// --design=github.com/itamartempel/yawarad/design
// --out=$(GOPATH)/src/github.com/itamartempel/yawarad
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// ListSnapshotPath computes a request path to the list action of snapshot.
func ListSnapshotPath() string {

	return fmt.Sprintf("/api/v1/cluster-branching/snapshots/")
}

// Retrive snapshots
func (c *Client) ListSnapshot(ctx context.Context, path string, clusterName *string, fromTime *int, limit *int, skip *int, toTime *int) (*http.Response, error) {
	req, err := c.NewListSnapshotRequest(ctx, path, clusterName, fromTime, limit, skip, toTime)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewListSnapshotRequest create the request corresponding to the list action endpoint of the snapshot resource.
func (c *Client) NewListSnapshotRequest(ctx context.Context, path string, clusterName *string, fromTime *int, limit *int, skip *int, toTime *int) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if clusterName != nil {
		values.Set("cluster_name", *clusterName)
	}
	if fromTime != nil {
		tmp37 := strconv.Itoa(*fromTime)
		values.Set("from_time", tmp37)
	}
	if limit != nil {
		tmp38 := strconv.Itoa(*limit)
		values.Set("limit", tmp38)
	}
	if skip != nil {
		tmp39 := strconv.Itoa(*skip)
		values.Set("skip", tmp39)
	}
	if toTime != nil {
		tmp40 := strconv.Itoa(*toTime)
		values.Set("to_time", tmp40)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// ShowSnapshotPath computes a request path to the show action of snapshot.
func ShowSnapshotPath(snapshotID string) string {
	param0 := snapshotID

	return fmt.Sprintf("/api/v1/cluster-branching/snapshots/%s", param0)
}

// Retrieve single cluster snapshot by id.
func (c *Client) ShowSnapshot(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowSnapshotRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowSnapshotRequest create the request corresponding to the show action endpoint of the snapshot resource.
func (c *Client) NewShowSnapshotRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
