// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "yawarad": CLI Commands
//
// Command:
// $ goagen
// --design=github.com/itamartempel/yawarad/design
// --out=$(GOPATH)/src/github.com/itamartempel/yawarad
// --version=v1.3.1

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/goadesign/goa"
	goaclient "github.com/goadesign/goa/client"
	uuid "github.com/goadesign/goa/uuid"
	"github.com/itamartempel/yawarad/client"
	"github.com/spf13/cobra"
	"log"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"
)

type (
	// CreateBranchClusterBranchingCommand is the command line data structure for the create-branch action of cluster-branching
	CreateBranchClusterBranchingCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}

	// ListBranchesClusterBranchingCommand is the command line data structure for the list-branches action of cluster-branching
	ListBranchesClusterBranchingCommand struct {
		// Filter branch by cluster name (contains)
		ClusterName string
		// Filter cluster branch by retriving all branch that was created after the giving value (Epoch time in milliseconds)
		FromTime int
		// limit the result set by giving value (default is 100 )
		Limit int
		// Filter branches by username of the reuqstor(contains)
		Requestor string
		// For pagenation, skip results by giving value
		Skip int
		// Filter branches by branch status
		Status string
		// Filter branches by team name (contains)
		Team string
		// Filter cluster branch by retriving all branch that was created before the giving value (Epoch time in milliseconds)
		ToTime int
		// Filter branches by branch type
		Type        string
		PrettyPrint bool
	}

	// ListClusterBranchesClusterBranchingCommand is the command line data structure for the list-cluster-branches action of cluster-branching
	ListClusterBranchesClusterBranchingCommand struct {
		// The cluster name to show
		ClusterName string
		// Filter cluster branch by retriving all branch that was created after the giving value (Epoch time in milliseconds)
		FromTime int
		// limit the result set by giving value (default is 100 )
		Limit int
		// Filter branches by username of the reuqstor(contains)
		Requestor string
		// For pagenation, skip results by giving value
		Skip int
		// Filter branches by branch status
		Status string
		// Filter branches by team name (contains)
		Team string
		// Filter cluster branch by retriving all branch that was created before the giving value (Epoch time in milliseconds)
		ToTime int
		// Filter branches by branch type
		Type        string
		PrettyPrint bool
	}

	// ListClusterSnapshotsClusterBranchingCommand is the command line data structure for the list-cluster-snapshots action of cluster-branching
	ListClusterSnapshotsClusterBranchingCommand struct {
		// The cluster name to show
		ClusterName string
		// Filter cluster snapshot by retriving all snapshot that was created after the giving value (Epoch time in milliseconds)
		FromTime int
		// limit the result set by giving value (default is 100)
		Limit int
		// For pagenation, skip results by giving value
		Skip int
		// Filter cluster snapshot by retriving all snapshot that was created before the giving value (Epoch time in milliseconds)
		ToTime      int
		PrettyPrint bool
	}

	// ListClustersClusterBranchingCommand is the command line data structure for the list-clusters action of cluster-branching
	ListClustersClusterBranchingCommand struct {
		// Filter by cluster name (contains)
		ClusterName string
		ClusterType string
		// limit the result set by giving value (default is 100)
		Limit int
		// For pagenation, skip results by giving value
		Skip        int
		PrettyPrint bool
	}

	// ListRequestTasksClusterBranchingCommand is the command line data structure for the list-request-tasks action of cluster-branching
	ListRequestTasksClusterBranchingCommand struct {
		// The request id to show
		RequestID   string
		PrettyPrint bool
	}

	// ListRequestsClusterBranchingCommand is the command line data structure for the list-requests action of cluster-branching
	ListRequestsClusterBranchingCommand struct {
		// Filter request by cluster name (contains)
		ClusterName string
		// Filter requests that was created after the giving value (Epoch time in milliseconds)
		FromTime int
		// limit the result set by giving value (default is 100 )
		Limit int
		// Filter branches by username of the reuqstor(contains)
		Requestor string
		// For pagenation, skip results by giving value
		Skip int
		// Filter requests by request state
		State string
		// Filter request that was created before the giving value (Epoch time in milliseconds)
		ToTime int
		// Filter request by request type
		Type        string
		PrettyPrint bool
	}

	// ListSnapshotBranchesClusterBranchingCommand is the command line data structure for the list-snapshot-branches action of cluster-branching
	ListSnapshotBranchesClusterBranchingCommand struct {
		// The snapshot id to show
		SnapshotID string
		// Filter cluster branch by retriving all branch that was created after the giving value (Epoch time in milliseconds)
		FromTime int
		// limit the result set by giving value (default is 100 )
		Limit int
		// Filter branches by username of the reuqstor(contains)
		Requestor string
		// For pagenation, skip results by giving value
		Skip int
		// Filter branches by branch status
		Status string
		// Filter branches by team name (contains)
		Team string
		// Filter cluster branch by retriving all branch that was created before the giving value (Epoch time in milliseconds)
		ToTime int
		// Filter branches by branch type
		Type        string
		PrettyPrint bool
	}

	// ListSnapshotsClusterBranchingCommand is the command line data structure for the list-snapshots action of cluster-branching
	ListSnapshotsClusterBranchingCommand struct {
		// Filter by cluster name (contains)
		ClusterName string
		// Filter cluster snapshot by retriving all snapshot that was created after the giving value (Epoch time in milliseconds)
		FromTime int
		// limit the result set by giving value (default is 100)
		Limit int
		// For pagenation, skip results by giving value
		Skip int
		// Filter cluster snapshot by retriving all snapshot that was created before the giving value (Epoch time in milliseconds)
		ToTime      int
		PrettyPrint bool
	}

	// ShowBrancheClusterBranchingCommand is the command line data structure for the show-branche action of cluster-branching
	ShowBrancheClusterBranchingCommand struct {
		// The branch id to show
		BranchID    string
		PrettyPrint bool
	}

	// ShowClusterClusterBranchingCommand is the command line data structure for the show-cluster action of cluster-branching
	ShowClusterClusterBranchingCommand struct {
		// The cluster name to show
		ClusterName string
		PrettyPrint bool
	}

	// ShowRequestClusterBranchingCommand is the command line data structure for the show-request action of cluster-branching
	ShowRequestClusterBranchingCommand struct {
		// The request id to show
		RequestID   string
		PrettyPrint bool
	}

	// ShowRequestTaskClusterBranchingCommand is the command line data structure for the show-request-task action of cluster-branching
	ShowRequestTaskClusterBranchingCommand struct {
		// The request id to show
		RequestID string
		// The request task name to show
		TaskName    string
		PrettyPrint bool
	}

	// ShowRequestTaskLogClusterBranchingCommand is the command line data structure for the show-request-task-log action of cluster-branching
	ShowRequestTaskLogClusterBranchingCommand struct {
		// The request id to show
		RequestID string
		// The request task name to show
		TaskName    string
		PrettyPrint bool
	}

	// ShowSnapshotClusterBranchingCommand is the command line data structure for the show-snapshot action of cluster-branching
	ShowSnapshotClusterBranchingCommand struct {
		// The snapshot id to show
		SnapshotID  string
		PrettyPrint bool
	}

	// SubscribeRequestChangesClusterBranchingCommand is the command line data structure for the subscribe-request-changes action of cluster-branching
	SubscribeRequestChangesClusterBranchingCommand struct {
		// The request id to show
		RequestID   string
		PrettyPrint bool
	}

	// SubscribeRequestTaskLogStreamClusterBranchingCommand is the command line data structure for the subscribe-request-task-log-stream action of cluster-branching
	SubscribeRequestTaskLogStreamClusterBranchingCommand struct {
		// The request id to show
		RequestID string
		// The request task name to show
		TaskName    string
		PrettyPrint bool
	}

	// UpdateBranchClusterBranchingCommand is the command line data structure for the update-branch action of cluster-branching
	UpdateBranchClusterBranchingCommand struct {
		Payload     string
		ContentType string
		PrettyPrint bool
	}
)

// RegisterCommands registers the resource action CLI commands.
func RegisterCommands(app *cobra.Command, c *client.Client) {
	var command, sub *cobra.Command
	command = &cobra.Command{
		Use:   "create-branch",
		Short: `Create a new branch`,
	}
	tmp1 := new(CreateBranchClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/branches"]`,
		Short: ``,
		Long: `

Payload example:

{
   "cluster_name": "my_cluster",
   "requestor": "iisraelly@wix.com",
   "snapshot_id": "Image_4946347",
   "team": "Booking",
   "type": "dr"
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp1.Run(c, args) },
	}
	tmp1.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp1.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-branches",
		Short: `Retrive branches`,
	}
	tmp2 := new(ListBranchesClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/branches"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp2.Run(c, args) },
	}
	tmp2.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp2.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-cluster-branches",
		Short: `Retrive branches of a specific cluster`,
	}
	tmp3 := new(ListClusterBranchesClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/clusters/CLUSTER_NAME/branches"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp3.Run(c, args) },
	}
	tmp3.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp3.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-cluster-snapshots",
		Short: `Retrive snapshots of a specific cluster`,
	}
	tmp4 := new(ListClusterSnapshotsClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/clusters/CLUSTER_NAME/snapshots"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp4.Run(c, args) },
	}
	tmp4.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp4.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-clusters",
		Short: `Retrieve all Available cluster that can be branch.`,
	}
	tmp5 := new(ListClustersClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/clusters"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp5.Run(c, args) },
	}
	tmp5.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp5.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-request-tasks",
		Short: `Retrive request tasks`,
	}
	tmp6 := new(ListRequestTasksClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/requests/REQUEST_ID/tasks"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp6.Run(c, args) },
	}
	tmp6.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp6.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-requests",
		Short: `Retrive requests`,
	}
	tmp7 := new(ListRequestsClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/requests"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp7.Run(c, args) },
	}
	tmp7.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp7.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-snapshot-branches",
		Short: `Retrive branches that was created from a specific snapshot`,
	}
	tmp8 := new(ListSnapshotBranchesClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/snapshots/SNAPSHOT_ID/branches"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp8.Run(c, args) },
	}
	tmp8.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp8.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "list-snapshots",
		Short: `Retrive snapshots`,
	}
	tmp9 := new(ListSnapshotsClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/snapshots"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp9.Run(c, args) },
	}
	tmp9.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp9.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show-branche",
		Short: `Retrieve single cluster branch by id.`,
	}
	tmp10 := new(ShowBrancheClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/branches/BRANCH_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp10.Run(c, args) },
	}
	tmp10.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp10.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show-cluster",
		Short: `Retrieve single cluster to be branch by name.`,
	}
	tmp11 := new(ShowClusterClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/clusters/CLUSTER_NAME"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp11.Run(c, args) },
	}
	tmp11.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp11.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show-request",
		Short: `Retrieve single request by id.`,
	}
	tmp12 := new(ShowRequestClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/requests/REQUEST_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp12.Run(c, args) },
	}
	tmp12.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp12.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show-request-task",
		Short: `Retrive a single request task by name`,
	}
	tmp13 := new(ShowRequestTaskClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/requests/REQUEST_ID/tasks/TASK_NAME"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp13.Run(c, args) },
	}
	tmp13.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp13.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show-request-task-log",
		Short: `Retrive a single request task by id`,
	}
	tmp14 := new(ShowRequestTaskLogClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/requests/REQUEST_ID/tasks/TASK_NAME/log"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp14.Run(c, args) },
	}
	tmp14.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp14.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "show-snapshot",
		Short: `Retrieve single cluster snapshot by id.`,
	}
	tmp15 := new(ShowSnapshotClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/snapshots/SNAPSHOT_ID"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp15.Run(c, args) },
	}
	tmp15.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp15.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "subscribe-request-changes",
		Short: `Subscribe to any changes that will happend to a single request by websocket`,
	}
	tmp16 := new(SubscribeRequestChangesClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/requests/REQUEST_ID/ws"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp16.Run(c, args) },
	}
	tmp16.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp16.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "subscribe-request-task-log-stream",
		Short: `Retrive a single request task by id`,
	}
	tmp17 := new(SubscribeRequestTaskLogStreamClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/requests/REQUEST_ID/tasks/TASK_NAME/log/ws"]`,
		Short: ``,
		RunE:  func(cmd *cobra.Command, args []string) error { return tmp17.Run(c, args) },
	}
	tmp17.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp17.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
	command = &cobra.Command{
		Use:   "update-branch",
		Short: `Create a new branch`,
	}
	tmp18 := new(UpdateBranchClusterBranchingCommand)
	sub = &cobra.Command{
		Use:   `cluster-branching ["/api/v1/cluster-branching/branches"]`,
		Short: ``,
		Long: `

Payload example:

{
   "comment": "Quia necessitatibus.",
   "operation": "expire_now"
}`,
		RunE: func(cmd *cobra.Command, args []string) error { return tmp18.Run(c, args) },
	}
	tmp18.RegisterFlags(sub, c)
	sub.PersistentFlags().BoolVar(&tmp18.PrettyPrint, "pp", false, "Pretty print response body")
	command.AddCommand(sub)
	app.AddCommand(command)
}

func intFlagVal(name string, parsed int) *int {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func float64FlagVal(name string, parsed float64) *float64 {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func boolFlagVal(name string, parsed bool) *bool {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func stringFlagVal(name string, parsed string) *string {
	if hasFlag(name) {
		return &parsed
	}
	return nil
}

func hasFlag(name string) bool {
	for _, arg := range os.Args[1:] {
		if strings.HasPrefix(arg, "--"+name) {
			return true
		}
	}
	return false
}

func jsonVal(val string) (*interface{}, error) {
	var t interface{}
	err := json.Unmarshal([]byte(val), &t)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func jsonArray(ins []string) ([]interface{}, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []interface{}
	for _, id := range ins {
		val, err := jsonVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, val)
	}
	return vals, nil
}

func timeVal(val string) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339, val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func timeArray(ins []string) ([]time.Time, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []time.Time
	for _, id := range ins {
		val, err := timeVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func uuidVal(val string) (*uuid.UUID, error) {
	t, err := uuid.FromString(val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func uuidArray(ins []string) ([]uuid.UUID, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []uuid.UUID
	for _, id := range ins {
		val, err := uuidVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func float64Val(val string) (*float64, error) {
	t, err := strconv.ParseFloat(val, 64)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func float64Array(ins []string) ([]float64, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []float64
	for _, id := range ins {
		val, err := float64Val(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

func boolVal(val string) (*bool, error) {
	t, err := strconv.ParseBool(val)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

func boolArray(ins []string) ([]bool, error) {
	if ins == nil {
		return nil, nil
	}
	var vals []bool
	for _, id := range ins {
		val, err := boolVal(id)
		if err != nil {
			return nil, err
		}
		vals = append(vals, *val)
	}
	return vals, nil
}

// Run makes the HTTP request corresponding to the CreateBranchClusterBranchingCommand command.
func (cmd *CreateBranchClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/v1/cluster-branching/branches"
	}
	var payload client.CreateBranchPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.CreateBranchClusterBranching(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *CreateBranchClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}

// Run makes the HTTP request corresponding to the ListBranchesClusterBranchingCommand command.
func (cmd *ListBranchesClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/v1/cluster-branching/branches"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListBranchesClusterBranching(ctx, path, stringFlagVal("cluster_name", cmd.ClusterName), intFlagVal("from_time", cmd.FromTime), intFlagVal("limit", cmd.Limit), stringFlagVal("requestor", cmd.Requestor), intFlagVal("skip", cmd.Skip), stringFlagVal("status", cmd.Status), stringFlagVal("team", cmd.Team), intFlagVal("to_time", cmd.ToTime), stringFlagVal("type", cmd.Type))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListBranchesClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var clusterName string
	cc.Flags().StringVar(&cmd.ClusterName, "cluster_name", clusterName, `Filter branch by cluster name (contains)`)
	var fromTime int
	cc.Flags().IntVar(&cmd.FromTime, "from_time", fromTime, `Filter cluster branch by retriving all branch that was created after the giving value (Epoch time in milliseconds)`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 100, `limit the result set by giving value (default is 100 )`)
	var requestor string
	cc.Flags().StringVar(&cmd.Requestor, "requestor", requestor, `Filter branches by username of the reuqstor(contains)`)
	var skip int
	cc.Flags().IntVar(&cmd.Skip, "skip", skip, `For pagenation, skip results by giving value`)
	var status string
	cc.Flags().StringVar(&cmd.Status, "status", status, `Filter branches by branch status`)
	var team string
	cc.Flags().StringVar(&cmd.Team, "team", team, `Filter branches by team name (contains)`)
	var toTime int
	cc.Flags().IntVar(&cmd.ToTime, "to_time", toTime, `Filter cluster branch by retriving all branch that was created before the giving value (Epoch time in milliseconds)`)
	var type_ string
	cc.Flags().StringVar(&cmd.Type, "type", type_, `Filter branches by branch type`)
}

// Run makes the HTTP request corresponding to the ListClusterBranchesClusterBranchingCommand command.
func (cmd *ListClusterBranchesClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/clusters/%v/branches", url.QueryEscape(cmd.ClusterName))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListClusterBranchesClusterBranching(ctx, path, intFlagVal("from_time", cmd.FromTime), intFlagVal("limit", cmd.Limit), stringFlagVal("requestor", cmd.Requestor), intFlagVal("skip", cmd.Skip), stringFlagVal("status", cmd.Status), stringFlagVal("team", cmd.Team), intFlagVal("to_time", cmd.ToTime), stringFlagVal("type", cmd.Type))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListClusterBranchesClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var clusterName string
	cc.Flags().StringVar(&cmd.ClusterName, "cluster_name", clusterName, `The cluster name to show`)
	var fromTime int
	cc.Flags().IntVar(&cmd.FromTime, "from_time", fromTime, `Filter cluster branch by retriving all branch that was created after the giving value (Epoch time in milliseconds)`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 100, `limit the result set by giving value (default is 100 )`)
	var requestor string
	cc.Flags().StringVar(&cmd.Requestor, "requestor", requestor, `Filter branches by username of the reuqstor(contains)`)
	var skip int
	cc.Flags().IntVar(&cmd.Skip, "skip", skip, `For pagenation, skip results by giving value`)
	var status string
	cc.Flags().StringVar(&cmd.Status, "status", status, `Filter branches by branch status`)
	var team string
	cc.Flags().StringVar(&cmd.Team, "team", team, `Filter branches by team name (contains)`)
	var toTime int
	cc.Flags().IntVar(&cmd.ToTime, "to_time", toTime, `Filter cluster branch by retriving all branch that was created before the giving value (Epoch time in milliseconds)`)
	var type_ string
	cc.Flags().StringVar(&cmd.Type, "type", type_, `Filter branches by branch type`)
}

// Run makes the HTTP request corresponding to the ListClusterSnapshotsClusterBranchingCommand command.
func (cmd *ListClusterSnapshotsClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/clusters/%v/snapshots", url.QueryEscape(cmd.ClusterName))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListClusterSnapshotsClusterBranching(ctx, path, intFlagVal("from_time", cmd.FromTime), intFlagVal("limit", cmd.Limit), intFlagVal("skip", cmd.Skip), intFlagVal("to_time", cmd.ToTime))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListClusterSnapshotsClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var clusterName string
	cc.Flags().StringVar(&cmd.ClusterName, "cluster_name", clusterName, `The cluster name to show`)
	var fromTime int
	cc.Flags().IntVar(&cmd.FromTime, "from_time", fromTime, `Filter cluster snapshot by retriving all snapshot that was created after the giving value (Epoch time in milliseconds)`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 100, `limit the result set by giving value (default is 100)`)
	var skip int
	cc.Flags().IntVar(&cmd.Skip, "skip", skip, `For pagenation, skip results by giving value`)
	var toTime int
	cc.Flags().IntVar(&cmd.ToTime, "to_time", toTime, `Filter cluster snapshot by retriving all snapshot that was created before the giving value (Epoch time in milliseconds)`)
}

// Run makes the HTTP request corresponding to the ListClustersClusterBranchingCommand command.
func (cmd *ListClustersClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/v1/cluster-branching/clusters"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListClustersClusterBranching(ctx, path, stringFlagVal("cluster_name", cmd.ClusterName), stringFlagVal("cluster_type", cmd.ClusterType), intFlagVal("limit", cmd.Limit), intFlagVal("skip", cmd.Skip))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListClustersClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var clusterName string
	cc.Flags().StringVar(&cmd.ClusterName, "cluster_name", clusterName, `Filter by cluster name (contains)`)
	var clusterType string
	cc.Flags().StringVar(&cmd.ClusterType, "cluster_type", clusterType, ``)
	cc.Flags().IntVar(&cmd.Limit, "limit", 100, `limit the result set by giving value (default is 100)`)
	var skip int
	cc.Flags().IntVar(&cmd.Skip, "skip", skip, `For pagenation, skip results by giving value`)
}

// Run makes the HTTP request corresponding to the ListRequestTasksClusterBranchingCommand command.
func (cmd *ListRequestTasksClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/requests/%v/tasks", url.QueryEscape(cmd.RequestID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListRequestTasksClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListRequestTasksClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var requestID string
	cc.Flags().StringVar(&cmd.RequestID, "request_id", requestID, `The request id to show`)
}

// Run makes the HTTP request corresponding to the ListRequestsClusterBranchingCommand command.
func (cmd *ListRequestsClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/v1/cluster-branching/requests"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListRequestsClusterBranching(ctx, path, stringFlagVal("cluster_name", cmd.ClusterName), intFlagVal("from_time", cmd.FromTime), intFlagVal("limit", cmd.Limit), stringFlagVal("requestor", cmd.Requestor), intFlagVal("skip", cmd.Skip), stringFlagVal("state", cmd.State), intFlagVal("to_time", cmd.ToTime), stringFlagVal("type", cmd.Type))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListRequestsClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var clusterName string
	cc.Flags().StringVar(&cmd.ClusterName, "cluster_name", clusterName, `Filter request by cluster name (contains)`)
	var fromTime int
	cc.Flags().IntVar(&cmd.FromTime, "from_time", fromTime, `Filter requests that was created after the giving value (Epoch time in milliseconds)`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 100, `limit the result set by giving value (default is 100 )`)
	var requestor string
	cc.Flags().StringVar(&cmd.Requestor, "requestor", requestor, `Filter branches by username of the reuqstor(contains)`)
	var skip int
	cc.Flags().IntVar(&cmd.Skip, "skip", skip, `For pagenation, skip results by giving value`)
	var state string
	cc.Flags().StringVar(&cmd.State, "state", state, `Filter requests by request state`)
	var toTime int
	cc.Flags().IntVar(&cmd.ToTime, "to_time", toTime, `Filter request that was created before the giving value (Epoch time in milliseconds)`)
	var type_ string
	cc.Flags().StringVar(&cmd.Type, "type", type_, `Filter request by request type`)
}

// Run makes the HTTP request corresponding to the ListSnapshotBranchesClusterBranchingCommand command.
func (cmd *ListSnapshotBranchesClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/snapshots/%v/branches", url.QueryEscape(cmd.SnapshotID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListSnapshotBranchesClusterBranching(ctx, path, intFlagVal("from_time", cmd.FromTime), intFlagVal("limit", cmd.Limit), stringFlagVal("requestor", cmd.Requestor), intFlagVal("skip", cmd.Skip), stringFlagVal("status", cmd.Status), stringFlagVal("team", cmd.Team), intFlagVal("to_time", cmd.ToTime), stringFlagVal("type", cmd.Type))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListSnapshotBranchesClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var snapshotID string
	cc.Flags().StringVar(&cmd.SnapshotID, "snapshot_id", snapshotID, `The snapshot id to show`)
	var fromTime int
	cc.Flags().IntVar(&cmd.FromTime, "from_time", fromTime, `Filter cluster branch by retriving all branch that was created after the giving value (Epoch time in milliseconds)`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 100, `limit the result set by giving value (default is 100 )`)
	var requestor string
	cc.Flags().StringVar(&cmd.Requestor, "requestor", requestor, `Filter branches by username of the reuqstor(contains)`)
	var skip int
	cc.Flags().IntVar(&cmd.Skip, "skip", skip, `For pagenation, skip results by giving value`)
	var status string
	cc.Flags().StringVar(&cmd.Status, "status", status, `Filter branches by branch status`)
	var team string
	cc.Flags().StringVar(&cmd.Team, "team", team, `Filter branches by team name (contains)`)
	var toTime int
	cc.Flags().IntVar(&cmd.ToTime, "to_time", toTime, `Filter cluster branch by retriving all branch that was created before the giving value (Epoch time in milliseconds)`)
	var type_ string
	cc.Flags().StringVar(&cmd.Type, "type", type_, `Filter branches by branch type`)
}

// Run makes the HTTP request corresponding to the ListSnapshotsClusterBranchingCommand command.
func (cmd *ListSnapshotsClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/v1/cluster-branching/snapshots"
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ListSnapshotsClusterBranching(ctx, path, stringFlagVal("cluster_name", cmd.ClusterName), intFlagVal("from_time", cmd.FromTime), intFlagVal("limit", cmd.Limit), intFlagVal("skip", cmd.Skip), intFlagVal("to_time", cmd.ToTime))
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ListSnapshotsClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var clusterName string
	cc.Flags().StringVar(&cmd.ClusterName, "cluster_name", clusterName, `Filter by cluster name (contains)`)
	var fromTime int
	cc.Flags().IntVar(&cmd.FromTime, "from_time", fromTime, `Filter cluster snapshot by retriving all snapshot that was created after the giving value (Epoch time in milliseconds)`)
	cc.Flags().IntVar(&cmd.Limit, "limit", 100, `limit the result set by giving value (default is 100)`)
	var skip int
	cc.Flags().IntVar(&cmd.Skip, "skip", skip, `For pagenation, skip results by giving value`)
	var toTime int
	cc.Flags().IntVar(&cmd.ToTime, "to_time", toTime, `Filter cluster snapshot by retriving all snapshot that was created before the giving value (Epoch time in milliseconds)`)
}

// Run makes the HTTP request corresponding to the ShowBrancheClusterBranchingCommand command.
func (cmd *ShowBrancheClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/branches/%v", url.QueryEscape(cmd.BranchID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowBrancheClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowBrancheClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var branchID string
	cc.Flags().StringVar(&cmd.BranchID, "branch_id", branchID, `The branch id to show`)
}

// Run makes the HTTP request corresponding to the ShowClusterClusterBranchingCommand command.
func (cmd *ShowClusterClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/clusters/%v", url.QueryEscape(cmd.ClusterName))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowClusterClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowClusterClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var clusterName string
	cc.Flags().StringVar(&cmd.ClusterName, "cluster_name", clusterName, `The cluster name to show`)
}

// Run makes the HTTP request corresponding to the ShowRequestClusterBranchingCommand command.
func (cmd *ShowRequestClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/requests/%v", url.QueryEscape(cmd.RequestID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowRequestClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowRequestClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var requestID string
	cc.Flags().StringVar(&cmd.RequestID, "request_id", requestID, `The request id to show`)
}

// Run makes the HTTP request corresponding to the ShowRequestTaskClusterBranchingCommand command.
func (cmd *ShowRequestTaskClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/requests/%v/tasks/%v", url.QueryEscape(cmd.RequestID), url.QueryEscape(cmd.TaskName))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowRequestTaskClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowRequestTaskClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var requestID string
	cc.Flags().StringVar(&cmd.RequestID, "request_id", requestID, `The request id to show`)
	var taskName string
	cc.Flags().StringVar(&cmd.TaskName, "task_name", taskName, `The request task name to show`)
}

// Run makes the HTTP request corresponding to the ShowRequestTaskLogClusterBranchingCommand command.
func (cmd *ShowRequestTaskLogClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/requests/%v/tasks/%v/log", url.QueryEscape(cmd.RequestID), url.QueryEscape(cmd.TaskName))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowRequestTaskLogClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowRequestTaskLogClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var requestID string
	cc.Flags().StringVar(&cmd.RequestID, "request_id", requestID, `The request id to show`)
	var taskName string
	cc.Flags().StringVar(&cmd.TaskName, "task_name", taskName, `The request task name to show`)
}

// Run makes the HTTP request corresponding to the ShowSnapshotClusterBranchingCommand command.
func (cmd *ShowSnapshotClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/snapshots/%v", url.QueryEscape(cmd.SnapshotID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.ShowSnapshotClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *ShowSnapshotClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var snapshotID string
	cc.Flags().StringVar(&cmd.SnapshotID, "snapshot_id", snapshotID, `The snapshot id to show`)
}

// Run establishes a websocket connection for the SubscribeRequestChangesClusterBranchingCommand command.
func (cmd *SubscribeRequestChangesClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/requests/%v/ws", url.QueryEscape(cmd.RequestID))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	ws, err := c.SubscribeRequestChangesClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}
	go goaclient.WSWrite(ws)
	goaclient.WSRead(ws)

	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *SubscribeRequestChangesClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var requestID string
	cc.Flags().StringVar(&cmd.RequestID, "request_id", requestID, `The request id to show`)
}

// Run establishes a websocket connection for the SubscribeRequestTaskLogStreamClusterBranchingCommand command.
func (cmd *SubscribeRequestTaskLogStreamClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = fmt.Sprintf("/api/v1/cluster-branching/requests/%v/tasks/%v/log/ws", url.QueryEscape(cmd.RequestID), url.QueryEscape(cmd.TaskName))
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	ws, err := c.SubscribeRequestTaskLogStreamClusterBranching(ctx, path)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}
	go goaclient.WSWrite(ws)
	goaclient.WSRead(ws)

	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *SubscribeRequestTaskLogStreamClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	var requestID string
	cc.Flags().StringVar(&cmd.RequestID, "request_id", requestID, `The request id to show`)
	var taskName string
	cc.Flags().StringVar(&cmd.TaskName, "task_name", taskName, `The request task name to show`)
}

// Run makes the HTTP request corresponding to the UpdateBranchClusterBranchingCommand command.
func (cmd *UpdateBranchClusterBranchingCommand) Run(c *client.Client, args []string) error {
	var path string
	if len(args) > 0 {
		path = args[0]
	} else {
		path = "/api/v1/cluster-branching/branches"
	}
	var payload client.UpdateBranchPayload
	if cmd.Payload != "" {
		err := json.Unmarshal([]byte(cmd.Payload), &payload)
		if err != nil {
			return fmt.Errorf("failed to deserialize payload: %s", err)
		}
	}
	logger := goa.NewLogger(log.New(os.Stderr, "", log.LstdFlags))
	ctx := goa.WithLogger(context.Background(), logger)
	resp, err := c.UpdateBranchClusterBranching(ctx, path, &payload, cmd.ContentType)
	if err != nil {
		goa.LogError(ctx, "failed", "err", err)
		return err
	}

	goaclient.HandleResponse(c.Client, resp, cmd.PrettyPrint)
	return nil
}

// RegisterFlags registers the command flags with the command line.
func (cmd *UpdateBranchClusterBranchingCommand) RegisterFlags(cc *cobra.Command, c *client.Client) {
	cc.Flags().StringVar(&cmd.Payload, "payload", "", "Request body encoded in JSON")
	cc.Flags().StringVar(&cmd.ContentType, "content", "", "Request content type override, e.g. 'application/x-www-form-urlencoded'")
}
