// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "yawarad": request-changes TestHelpers
//
// Command:
// $ goagen
// --design=github.com/itamartempel/yawarad/design
// --out=$(GOPATH)/src/github.com/itamartempel/yawarad
// --version=v1.3.1

package test
